name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CYPHERS=${{ secrets.CYPHERS }}
            DNF=${{ secrets.DNF }}

      - name: Get existing container ID
        id: get_container
        run: |
          CONTAINER_NAME="${{ github.event.repository.name }}"
          
          RESPONSE=$(curl -s "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENV_NO }}/docker/containers/json?all=true" \
          -H "X-API-KEY: ${{ secrets.PORTAINER_TOKEN }}")
          
          if echo "$RESPONSE" | jq empty 2>/dev/null; then
          CONTAINER_ID=$(echo "$RESPONSE" | jq -r '
          .[] |
          select(.Names[]? | test("^/'$CONTAINER_NAME'$")) |
          .Id // empty
          ' 2>/dev/null)
          
          if [ -z "$CONTAINER_ID" ] || [ "$CONTAINER_ID" = "null" ]; then
          CONTAINER_ID=""
          fi
          else
          CONTAINER_ID=""
          fi
          
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT
          echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT

      - name: Delete existing container
        if: steps.get_container.outputs.container_id != '' && steps.get_container.outputs.container_id != 'null'
        run: |
          curl -s -X DELETE "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENV_NO }}/docker/containers/${{ steps.get_container.outputs.container_id }}?force=true" \
            -H "X-API-KEY: ${{ secrets.PORTAINERTOKEN }}"

      - name: Pull latest image
        run: |
          REGISTRY_ENCODED=$(echo "${{ env.REGISTRY }}" | sed 's|/|%2F|g')
          IMAGE_ENCODED=$(echo "${{ env.IMAGE_NAME }}" | sed 's|/|%2F|g')
          
          curl -s -X POST "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENV_NO }}/docker/images/create?fromImage=${REGISTRY_ENCODED}%2F${IMAGE_ENCODED}&tag=main" \
          -H "X-API-KEY: ${{ secrets.PORTAINER_TOKEN }}" \
          -H "Referer: ${{ secrets.PORTAINE_RURL }}"

      - name: Create new container
        run: |
          curl -s -X POST "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENV_NO }}/docker/containers/create?name=${{ steps.get_container.outputs.container_name }}" \
            -H "X-API-KEY: ${{ secrets.PORTAINER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"Image\": \"${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main\",
              \"HostConfig\": {
                \"NetworkMode\": \"local\",
                \"PortBindings\": {
                  \"80/tcp\": [{\"HostPort\": \"80\"}]
                },
                \"RestartPolicy\": {
                  \"Name\": \"unless-stopped\"
                }
              }
            }"

      - name: Start container
        run: |
          curl -s -X POST "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENV_NO }}/docker/containers/${{ steps.get_container.outputs.container_name }}/start" \
            -H "X-API-KEY: ${{ secrets.PORTAINER_TOKEN }}"